"""auto-vote

Revision ID: 2c3c50f524fd
Revises: 970d281b3110
Create Date: 2022-10-13 16:27:09.818583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c3c50f524fd'
down_revision = '970d281b3110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fvotes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['fposts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['fusers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fvotes')
    # ### end Alembic commands ###
